#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
#

Name:       harbour-roothub

# >> macros
# << macros

%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^lib.*$

Summary:    RooThub is a native GitHub client for Sailfish OS
Version:    0.4.0
Release:    1
Group:      Qt/Qt
License:    GPL-3.0
URL:        https://github.com/RootGPT-YouTube/RooThub-SailfishOS
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-roothub.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   nemo-qml-plugin-configuration-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
RooThub is a native GitHub client for Sailfish OS. Browse repositories,
read and manage issues and pull requests, follow notifications, search
GitHub and view profiles. Sign in with the GitHub Device Flow or a
Personal Access Token.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5

%make_build

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
